In [1]:

'''import kagglehub

# Download latest version
path = kagglehub.dataset_download("pythonafroz/solar-power")

print("Path to dataset files:", path)'''

'import kagglehub\n\n# Download latest version\npath = kagglehub.dataset_download("pythonafroz/solar-power")\n\nprint("Path to dataset files:", path)'

In [2]:
'''!kaggle datasets list -s "solar-power"'''

'!kaggle datasets list -s "solar-power"'

In [3]:
'''!kaggle datasets download -d pythonafroz/solar-power --unzip -p > solar_power.zip solar_power_data'''

'!kaggle datasets download -d pythonafroz/solar-power --unzip -p > solar_power.zip solar_power_data'

In [4]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.precision', 3)

In [6]:
# Load and explore the dataset
power_data = pd.read_csv('solar_power_data/Plant_1_Generation_Data.csv')
weather_data = pd.read_csv('solar_power_data/Plant_1_Weather_Sensor_Data.csv')

print('='*100)
print("power demand:\n", power_data.head())
print('='*100)
print('whether data:\n', weather_data.head())

====================================================================================================
power demand:
           DATE_TIME  PLANT_ID       SOURCE_KEY  DC_POWER  AC_POWER  \
0  15-05-2020 00:00   4135001  1BY6WEcLGh8j5v7       0.0       0.0
1  15-05-2020 00:00   4135001  1IF53ai7Xc0U56Y       0.0       0.0
2  15-05-2020 00:00   4135001  3PZuoBAID5Wc2HD       0.0       0.0
3  15-05-2020 00:00   4135001  7JYdWkrLSPkdwr4       0.0       0.0
4  15-05-2020 00:00   4135001  McdE0feGgRqW7Ca       0.0       0.0

   DAILY_YIELD  TOTAL_YIELD
0          0.0    6.260e+06
1          0.0    6.184e+06
2          0.0    6.988e+06
3          0.0    7.603e+06
4          0.0    7.159e+06
====================================================================================================
whether data:
              DATE_TIME  PLANT_ID       SOURCE_KEY  AMBIENT_TEMPERATURE  \
0  2020-05-15 00:00:00   4135001  HmiyD2TTLFNqkNe               25.184
1  2020-05-15 00:15:00   4135001  HmiyD2TTLFNqkNe               25.085
2  2020-05-15 00:30:00   4135001  HmiyD2TTLFNqkNe               24.936
3  2020-05-15 00:45:00   4135001  HmiyD2TTLFNqkNe               24.846
4  2020-05-15 01:00:00   4135001  HmiyD2TTLFNqkNe               24.622

   MODULE_TEMPERATURE  IRRADIATION
0              22.858          0.0
1              22.762          0.0
2              22.592          0.0
3              22.361          0.0
4              22.165          0.0

In [7]:
print('power_data shape:', power_data.shape)
print('weather_data shape:', weather_data.shape)

power_data shape: (68778, 7)
weather_data shape: (3182, 6)

In [8]:
print("-"*100)
print("null values in power_data:\n", power_data.isnull().sum())
print("-"*100)
print("null values in weather_data:\n", weather_data.isnull().sum())
print("-"*100)

----------------------------------------------------------------------------------------------------
null values in power_data:
 DATE_TIME      0
PLANT_ID       0
SOURCE_KEY     0
DC_POWER       0
AC_POWER       0
DAILY_YIELD    0
TOTAL_YIELD    0
dtype: int64
----------------------------------------------------------------------------------------------------
null values in weather_data:
 DATE_TIME              0
PLANT_ID               0
SOURCE_KEY             0
AMBIENT_TEMPERATURE    0
MODULE_TEMPERATURE     0
IRRADIATION            0
dtype: int64
----------------------------------------------------------------------------------------------------

In [9]:
print("data types in power_data:\n", power_data.dtypes)
print("-"*100)
print("data types in weather_data:\n", weather_data.dtypes)
print("-"*100)

data types in power_data:
 DATE_TIME       object
PLANT_ID         int64
SOURCE_KEY      object
DC_POWER       float64
AC_POWER       float64
DAILY_YIELD    float64
TOTAL_YIELD    float64
dtype: object
----------------------------------------------------------------------------------------------------
data types in weather_data:
 DATE_TIME               object
PLANT_ID                 int64
SOURCE_KEY              object
AMBIENT_TEMPERATURE    float64
MODULE_TEMPERATURE     float64
IRRADIATION            float64
dtype: object
----------------------------------------------------------------------------------------------------

In [10]:
# convert the 'DATE_TIME' column to datetime format
power_data['DATE_TIME'] = pd.to_datetime(power_data['DATE_TIME'],  errors='coerce')
weather_data['DATE_TIME'] = pd.to_datetime(weather_data['DATE_TIME'], errors='coerce')

In [11]:
print("data types in power_data:\n", power_data.dtypes)
print("-"*100)
print("data types in weather_data:\n", weather_data.dtypes)
print("-"*100)

data types in power_data:
 DATE_TIME      datetime64[ns]
PLANT_ID                int64
SOURCE_KEY             object
DC_POWER              float64
AC_POWER              float64
DAILY_YIELD           float64
TOTAL_YIELD           float64
dtype: object
----------------------------------------------------------------------------------------------------
data types in weather_data:
 DATE_TIME              datetime64[ns]
PLANT_ID                        int64
SOURCE_KEY                     object
AMBIENT_TEMPERATURE           float64
MODULE_TEMPERATURE            float64
IRRADIATION                   float64
dtype: object
----------------------------------------------------------------------------------------------------

In [12]:
power_data['DATE_TIME'].head()

0   2020-05-15
1   2020-05-15
2   2020-05-15
3   2020-05-15
4   2020-05-15
Name: DATE_TIME, dtype: datetime64[ns]

In [13]:
weather_data['DATE_TIME'].head()

0   2020-05-15 00:00:00
1   2020-05-15 00:15:00
2   2020-05-15 00:30:00
3   2020-05-15 00:45:00
4   2020-05-15 01:00:00
Name: DATE_TIME, dtype: datetime64[ns]

In [14]:
# check unique values in each column
for col in power_data.columns:
    unique_values = power_data[col].nunique()
    print(f"Column '{col}' has {unique_values} unique values.")

print("-"*100)
for col in weather_data.columns:
    unique_values = weather_data[col].nunique()
    print(f"Column '{col}' has {unique_values} unique values.")

Column 'DATE_TIME' has 3158 unique values.
Column 'PLANT_ID' has 1 unique values.
Column 'SOURCE_KEY' has 22 unique values.
Column 'DC_POWER' has 32909 unique values.
Column 'AC_POWER' has 32686 unique values.
Column 'DAILY_YIELD' has 29900 unique values.
Column 'TOTAL_YIELD' has 37267 unique values.
----------------------------------------------------------------------------------------------------
Column 'DATE_TIME' has 3182 unique values.
Column 'PLANT_ID' has 1 unique values.
Column 'SOURCE_KEY' has 1 unique values.
Column 'AMBIENT_TEMPERATURE' has 3182 unique values.
Column 'MODULE_TEMPERATURE' has 3182 unique values.
Column 'IRRADIATION' has 1758 unique values.

In [15]:
df_solar = pd.merge(power_data.drop(columns = ['PLANT_ID']), weather_data.drop(columns = ['PLANT_ID', 'SOURCE_KEY']), on='DATE_TIME')

In [16]:
df_solar.sample(5).style.background_gradient('coolwarm')

In [17]:
df_solar.shape

(68774, 9)

In [18]:
df_solar.isnull().sum()

DATE_TIME              0
SOURCE_KEY             0
DC_POWER               0
AC_POWER               0
DAILY_YIELD            0
TOTAL_YIELD            0
AMBIENT_TEMPERATURE    0
MODULE_TEMPERATURE     0
IRRADIATION            0
dtype: int64

In [19]:
#extract date features from date_time column
df_solar['date'] = df_solar['DATE_TIME'].dt.date
df_solar['month'] = df_solar['DATE_TIME'].dt.month
df_solar['time'] = df_solar['DATE_TIME'].dt.time
df_solar['day'] = df_solar['DATE_TIME'].dt.day
df_solar['week'] = df_solar['DATE_TIME'].dt.isocalendar().week

In [21]:
df_solar.sample(5)

,DATE_TIME,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,date,month,time,day,week
11345,2020-05-20 18:00:00,bvBOhCH3iADSZry,766.875,74.400,8112.750,6.355e+06,28.524,29.695,0.060,2020-05-20,5,18:00:00,20,21
51329,2020-06-09 17:15:00,1IF53ai7Xc0U56Y,2661.571,261.043,8038.714,6.380e+06,28.551,33.272,0.195,2020-06-09,6,17:15:00,9,24
17740,2020-05-24 06:45:00,wCURE6d3bPkepu2,1155.000,112.329,42.857,6.848e+06,24.018,23.685,0.086,2020-05-24,5,06:45:00,24,21
41028,2020-06-04 18:15:00,zBIq5rxdHJRwDNY,300.714,29.057,8232.714,6.493e+06,25.880,25.645,0.023,2020-06-04,6,18:15:00,4,23
47759,2020-06-08 00:30:00,uHbuxQJl8lW7ozc,0.000,0.000,0.000,7.217e+06,23.057,21.816,0.000,2020-06-08,6,00:30:00,8,24

In [22]:
# add hour and minute features
df_solar['hour'] = df_solar['DATE_TIME'].dt.hour
df_solar['minute'] = df_solar['DATE_TIME'].dt.minute
df_solar['total_minutes_pass'] = df_solar['hour'] * 60 + df_solar['minute']

# add date as string column
df_solar['date_str'] = df_solar['date'].astype(str)
df_solar['hours_str'] = df_solar['hour'].astype(str)
df_solar['time_str'] = df_solar['time'].astype(str)

In [23]:
df_solar.sample(5)

,DATE_TIME,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,date,month,time,day,week,hour,minute,total_minutes_pass,date_str,hours_str,time_str
2760,2020-05-16 11:00:00,sjndEbLyjtCKgGv,7537.143,737.814,2255.000,7.025e+06,29.155,49.156,0.575,2020-05-16,5,11:00:00,16,20,11,0,660,2020-05-16,11,11:00:00
59343,2020-06-13 12:15:00,YxYtjZvoooNbGkE,10834.250,1057.800,4379.375,7.395e+06,29.873,53.626,0.889,2020-06-13,6,12:15:00,13,24,12,15,735,2020-06-13,12,12:15:00
66796,2020-06-17 01:00:00,3PZuoBAID5Wc2HD,0.000,0.000,0.000,7.231e+06,22.771,21.472,0.000,2020-06-17,6,01:00:00,17,25,1,0,60,2020-06-17,1,01:00:00
38779,2020-06-03 16:45:00,rGa61gmuvPhdLxV,4982.429,488.314,7413.714,7.257e+06,26.611,32.195,0.293,2020-06-03,6,16:45:00,3,23,16,45,1005,2020-06-03,16,16:45:00
45260,2020-06-06 20:15:00,McdE0feGgRqW7Ca,0.000,0.000,0.000,7.331e+06,22.393,20.395,0.000,2020-06-06,6,20:15:00,6,23,20,15,1215,2020-06-06,20,20:15:00